# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cd611cd9fd0734bc5ce1d3124b9a28f64d008d325d43c3c6e4ab81e78ceba022c6f7c612a9848458050e3ec8431d4321a79de69832dc3b7352cc232de5076c7
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: 768e169479172d65117cf1b558a2c84fe9d217b722e71448f7df0121abf4a8897cd9b2df7ce7fe1f2a86fd140a7d386598caee29de6b254fe7736f82c3674e0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
